env:
  browser: true
  commonjs: true
  es2021: true
#extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
extends:
  - 'airbnb-base'
#  - 'plugin:jest/recommended'
